apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-local
  namespace: event-mesh-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamodb-local
  template:
    metadata:
      labels:
        app: dynamodb-local
    spec:
      containers:
      - name: dynamodb-local
        image: amazon/dynamodb-local:2.0.0
        ports:
        - containerPort: 8000
        command:
        - java
        - -jar
        - DynamoDBLocal.jar
        - -inMemory
        - -sharedDb
        - -port
        - "8000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          tcpSocket:
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: dynamodb-local
  namespace: event-mesh-system
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: dynamodb-local

---
apiVersion: batch/v1
kind: Job
metadata:
  name: dynamodb-setup
  namespace: event-mesh-system
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: dynamodb-setup
        image: amazon/aws-cli:2.13.0
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "dummy"
        - name: AWS_SECRET_ACCESS_KEY
          value: "dummy"
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        command:
        - sh
        - -c
        - |
          sleep 30
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name movimiento-inventario-events \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
              AttributeName=timestamp,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
              AttributeName=timestamp,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name movimiento-inventario-read \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name orden-compra-events \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
              AttributeName=timestamp,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
              AttributeName=timestamp,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name orden-compra-read \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name proveedor-events \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
              AttributeName=timestamp,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
              AttributeName=timestamp,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name proveedor-read \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name ingreso-inventario-events \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
              AttributeName=timestamp,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
              AttributeName=timestamp,KeyType=RANGE \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb create-table \
            --region us-east-1 \
            --endpoint-url http://dynamodb-local:8000 \
            --table-name ingreso-inventario-read \
            --attribute-definitions \
              AttributeName=id,AttributeType=S \
            --key-schema \
              AttributeName=id,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST
          
          aws dynamodb list-tables --region us-east-1 --endpoint-url http://dynamodb-local:8000
